config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_jobs, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:category].blank?
    @jobs = Job.all.order("created_at DESC")
   else
     @category_id = Category.find_by(name: params[:category]).id
     @jobs = Job.where(category_id: @category_id).order("created_at DESC")
   end
  end
  
  def show
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(jobs_params)
    
    if @job.save
      redirect_to @job
    else
      render "New"
    end  
  end


  def edit
  end
  
  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render "Edit"
    end
  end
  
  def destroy
    @job.destroy
    redirect_to root_path
  end
  
  private
  
  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url, :category_id)
  end
  
  def find_jobs
    @job = Job.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
  =f.collection_select :category_id, Category.all, :id, :name, {promt: "CHoose a category" }
  = f.input :title, label: "job title"
  = f.input :description, label: "job description"
  = f.input :company, label: "your comoany"
  = f.input :url, label: "Link to job"
  %br/
  = f.button :submit

app/views/jobs/edit.html.haml
%h1 編集バイト

= render 'form'

= link_to "back", root_path

app/views/jobs/index.html.haml
- @jobs.each do |job|
  %h2= link_to job.title, job
  %p= job.company
  
  = link_to "New job", new_job_path

app/views/jobs/new.html.haml
%h1 新規バイト

= render 'form'

= link_to "back", root_path

app/views/jobs/show.html.haml
%h1= @job.title
%p= @job.description
%p= @job.company

= link_to "HOME", root_path
= link_to "編集", edit_job_path(@job)
= link_to "削除", job_path(@job), method: :delete, data: { confirm: "削除しますか?" }

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
    %title アルバイト
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

%body
    - Category.all.each do |category|   
        = link_to category.name, jobs_path(category: category.name)
    
    = yield